config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :tasks do
    member do
      patch :toggle
    end
  end
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy, :toggle]
  # 共通化

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to root_path
    else
      render 'edit', status: :unprocessable_entity
                    # バリデーションエラーの場合に返す
    end
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path, status: :see_other
    # 303 See Other 確認ページなど別なページにリンクする
  end

  # リロードしてもcheck boxの状態が保持される
  def toggle
    # @task = Task.find(params[:id])
    @task.update(completed: !@task.completed)
    render turbo_stream: turbo_stream.replace(
      @task,
      partial: 'completed',
      locals: { task: @task}
      )
  end

  private

  def task_params
    params.require(:task).permit(:title)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewTodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_completed.html.erb
<%= turbo_frame_tag task do %>
<!--jquery非同期のような機能-->
  <%= form_with model: task, url: toggle_task_path(task) do |f| %>
    <li>
      <span class=" <%= task.completed? ? 'completed' : '' %>">
        <%= f.check_box :completed,
        onchange: 'this.form.requestSubmit()' %>

        <%= task.title %>
        <%= link_to '[edit]', edit_task_path(task), date: { turbo_frame: '_top'} %>
        <%= link_to '[destroy]', task_path(task),
        data: { turbo_method: 'delete',
        turbo_confirm: 'Are you sure?'} %>
        <!--turboつけることで高速に処理。rails7から対応-->
      </span>
    </li>

  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% if @task.errors.any? %>
      <%= @task.errors.messages[:title][0] %>
    <% end %>
  </p>
  <p>
    <%=form.submit %>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit</h1>
<%= render partial: 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<%= link_to 'new', new_task_path %>
<ul>
  <% @tasks.each do |task| %>
      <%= render 'completed', task: task %>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>New</h1>
<%= render partial: 'form' %>
<!--partialオプション、一部のファイルのみの時使う-->